FROM centos:base

WORKDIR /opt

COPY start.sh /opt
COPY redis-6.0.8.tar.gz /opt

RUN mkdir /opt/redis && tar xzf redis-6.0.8.tar.gz -C /opt/redis \
    && rm -rf redis-6.0.8.tar.gz \
    && cd /opt/redis/redis-6.0.8 \
    && make \
    && chmod 750 /opt/start.sh


CMD ["/opt/start.sh"]