FROM centos:1.1.0



RUN yum -y install wget gcc automake autoconf libtool make \
    && wget http://download.redis.io/releases/redis-6.0.8.tar.gz \
    && tar xzf redis-6.0.8.tar.gz -d /opt/redis \
    && cd /opt/redis/redis-6.0.8 \
    && make


WORKDIR /opt

CMD ["src/redis-server"]